name: 'actions-setup-re'
description: 'Setup the Re build system'
inputs:
  re-version:
    description: 'The version of Re to setup. E.g. 0.2.0'
    default: 'latest'
  github-api-token:
    description: 'GitHub token to use when retrieving version info'
    default: '${{ github.token }}'
  setup-cmake:
    description: 'Set up CMake and Ninja to build CMake projects using Re'
    default: 'true'
  internal-action-self-path:
    description: "[Internal] The path to the action's root directory. You shouldn't set this property."
    default: '${{ github.action_path }}'
runs:
  using: 'composite'
  steps:
    # - uses: actions/setup-node@v3
    #   with:
    #     node-version: '16.x'

    - run: 'cd ${{ inputs.internal-action-self-path }} && node ./dist/index.js'
      shell: bash
        
    - uses: jwlawson/actions-setup-cmake@v1.13
      if: ${{ inputs.setup-cmake == 'true' && runner.os != 'Windows' }}

    - uses: seanmiddleditch/gha-setup-ninja@v3
      if: ${{ inputs.setup-cmake == 'true' && runner.os != 'Windows' }}
    
    # Sets up the MSVC dev command prompt in case we're running Windows
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
      with:
        arch: ${{ inputs.arch }}
