name: 'actions-setup-re'
description: 'Setup the Re build system'
inputs:
  re-version:
    description: 'The version of Re to setup. E.g. 0.2.0'
    default: ''
  github-api-token:
    description: 'GitHub token to use when retrieving version info'
    default: '${{ github.token }}'
  use-32bit:
    description: 'Force using 32 bit version of Re, instead of looking for 64 bit version'
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
