on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  action_tests:
    runs-on: ${{ matrix.os }}
    name: Action Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        re_ver: ['0.2.1']

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Re
      uses: ./
      id: setup
      with:
        re-version: ${{ matrix.re_ver }}

    - name: Run `re version`
      shell: bash
      if: matrix.re_ver != ''
      run: re version