on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  action_tests:
    runs-on: ${{ matrix.os }}
    name: Action Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        re_ver: ['0.2.1']

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Re
      uses: ./
      id: setup
      with:
        re-version: ${{ matrix.re_ver }}

    - name: Run `re version`
      shell: bash
      if: matrix.re_ver != ''
      run: re version

  unit_tests:
    runs-on: ${{ matrix.os }}
    name: Unit Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install node dependencies
      run: npm install

    - name: Check `npm run format` has been run
      run: |
        npm run format
        git diff --quiet src/

    - name: Check `npm run package` has been run
      run: |
        npm run package
        git diff --quiet dist/

    # - name: Run tests
    #   run: npm test